### PR TITLE
update dependency packages and add readme file

### PR DESCRIPTION
**Pull request by gasolin**
- run `bower update` to sync demo page to current status.
- add readme to address issue #1 (this repo is used for demo, not for bower install) #3 (add instruction about enable preference on desktop and fxos device)

### CODE REVIEW

**Comment by wilsonpage** [comment]
Need to update a `#dev` references in bower.json to `#master`, then run `bower update` again.

#### Currently broken:
- `gaia-switch`
- `gaia-text-input`
- `gaia-picker`

Make sure JS console is error free before pushing again :)

**Comment by gasolin** [comment]
Thanks for double check, I found the toolbar master has a deprecated dependency 
https://github.com/gaia-components/gaia-toolbar/blob/master/bower.json

so I update it unchanged. Now JS console is error free\* :stuck_out_tongue:
- (gaia-picker error is not fixed yet since current version already has this issue, would need update that package)

**Comment by wilsonpage** [comment]
Still getting console error related to gaia-picker.

screen shot 2015-05-11 at 14 22 19

**Comment by gasolin** [comment]
That's exactly what I said in last comment :grin: 

It's not a new issue introduced by this PR (current page also has this issue) and might need to be fixed in `gaia-picker` first.

**Comment by wilsonpage** [comment]
Ahhh, sorry, my bad! :speak_no_evil: 

Let's land this :smiley:

**Pull request merged**
